
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/anurag-nikhil/reservation-config-server-properties.git

server:
  port: 8071